### ISSUE TITLE
Code Improvement

### ISSUE THREAD

**Issue by DerekJxy** [dhillonks/cli-ssg#3]
For the __'generateHtml.js'__,
__Line 15__ _const lines = data.split(/\r?\n/);_

This line of code __separate__ the article in the txt file __sentences by sentences__.
You can change the code like:
 _const lines = data.split(/\r?\n\r?\n/);_

So that you can __separate__ the article in the txt file __paragraphs by paragraphs__, which will make you webpage looks better.

**Comment by dhillonks** [comment]
Separating the file line by line and storing it in `lines` is intentional. The suggestion is a different way of approaching the problem but I don't see it offering any tangible improvement at this point (would rather hamper upgradability). The styling is done through the CSS either way, so also not sure how that improves.
